### ISSUE TITLE
IDEA -- Developing Repo Wiki

### ISSUE THREAD

**Issue by callahantiff** [Knowledge-Graph-Hub/kg-emerging-viruses#1]
Perhaps we can use the Wiki associated with this repo as means to help keep some of the information/resources/data/articles organized? We could also expand it to provide an introduction for people who want to join the effort and provide introductory information that would help them quickly get up to speed. We can also sue it to link out to things like the flatten the curve website.

If that would be helpful, I'm happy to mock out some potential pages and start creating them. Let me know if that's something worth doing!

**Comment by deepakunni3** [comment]
@callahantiff Yes, that is a great idea. I was debating whether we use GitHub Wiki or use GitHub pages to serve markdown content. We can start with the Wiki and move to GitHub pages if things get unweildy.

**Comment by callahantiff** [comment]
> @callahantiff Yes, that is a great idea. I was debating whether we use GitHub Wiki or use GitHub pages to serve markdown content. We can start with the Wiki and move to GitHub pages if things get unweildy.

 I think that's a great idea @deepakunni3! I'm happy to work on either. I will work on some basic layouts ideas today and post the ideas here later today/tonight.

**Comment by callahantiff** [comment]
Adding list of resources here to incorporate into Wiki:

> There has been discussions in the Translator project on drug repurposing and Matt Might (University of Alabama, Birmingham) has made this resource available: https://docs.google.com/document/d/1axacpu4hsAP2vv3gVgXtiPBg-jIJu5TEHP_UkGQBQZs/edit#heading=h.icmm2sh44tl
> 
> It highlights potential drugs that can be repurposed for SARS-CoV-2.
> The idea is to pick a few drugs that can work (in isolation or in combination) in treating and preventing COVID-19.

> This is a paper about a heterogeneous network for repurposing
> https://pubs.rsc.org/en/content/articlelanding/2020/SC/C9SC04336E#!divAbstract

https://www.nature.com/articles/s41421-020-0153-3

**Comment by deepakunni3** [comment]
@callahantiff I would not recommend adding this:
```
There has been discussions in the Translator project on drug repurposing and Matt Might (University of Alabama, Birmingham) has made this resource available: https://docs.google.com/document/d/1axacpu4hsAP2vv3gVgXtiPBg-jIJu5TEHP_UkGQBQZs/edit#heading=h.icmm2sh44tl

It highlights potential drugs that can be repurposed for SARS-CoV-2.
The idea is to pick a few drugs that can work (in isolation or in combination) in treating and preventing COVID-19.
```
Note until we discuss with Matt Might about it. That document was supposed to be internal ;)

**Comment by callahantiff** [comment]
Sorry about that @deepakunni3, I should have asked! I have removed the comment :/

**Comment by deepakunni3** [comment]
No worries :)

**Comment by callahantiff** [comment]
OK, rough draft outline for the [Wiki](https://github.com/kg-emerging-viruses/kg-emerging-viruses/wiki) just to get us going:

<br>

## Project Wiki
- Home
- How to Help   

## Projects
- Corona KG Hub 
- Virus Phylogeny Similarity   
- _<<project 3>>_   

## Resources   
- Data Sources  
- Publications  
- Other Work & Efforts

**Comment by justaddcoffee** [comment]
Thanks @callahantiff! Closing this, since we've got the wiki started now. Let's flesh this out more as we go
