### ISSUE TITLE
CoV-associated host proteins 

### ISSUE THREAD

**Issue by pnrobinson** [Knowledge-Graph-Hub/kg-emerging-viruses#2]
Assemble a list of all CoV-associated proteins
Supplemental table 3 of this paper: https://www.nature.com/articles/s41421-020-0153-3 has a list

These are human proteins are either the direct targets of HCoV proteins or are involved in crucial pathways of HCoV infection. 

Question -- do we need a small ontology of terms that describe the way that a human protein interacts with corona  virus?

**Comment by justaddcoffee** [comment]
> Question -- do we need a small ontology of terms that describe the way that a human protein interacts with corona virus?

Yes, I think we do need to consider how to model this and other such interactions. 

I'm nearly done with this ingest, so for now I'm going to use [`interacts_with`](http://purl.obolibrary.org/obo/RO_0002434). 

@cmungall thoughts on this?

**Comment by justaddcoffee** [comment]
Addressed with #20
