### ISSUE TITLE
Human proteins that interact with Corona

### ISSUE THREAD

**Issue by pnrobinson** [Knowledge-Graph-Hub/kg-emerging-viruses#4]
Supplementary Table S3. HCoV-associated host proteins with references
in [Zeng et al](https://pubs.rsc.org/en/content/articlelanding/2020/SC/C9SC04336E#!divAbstract) collects information from several PubMed articles. The table is available as part of a PDF document but should be easily parsable. 
Also check the literature if there are new papers with new interacting human host proteins.

**Comment by justaddcoffee** [comment]
Hi @pnrobinson  - can you confirm that what we want to ingest here is these two tables:
http://www.rsc.org/suppdata/c9/sc/c9sc04336e/c9sc04336e2.xlsx
http://www.rsc.org/suppdata/c9/sc/c9sc04336e/c9sc04336e3.xlsx

**Comment by pnrobinson** [comment]
I think the first table contains predictions (we do not want to ingest this). The second table contains an excerpt of stuff we want to ingest from drug central!

**Comment by justaddcoffee** [comment]
> Supplementary Table S3. HCoV-associated host proteins with references
in Zeng et al collects information from several PubMed articles. The table is available as part of a PDF document but should be easily parsable.

Sorry to be dense, but I'm still confused - Table S3 doesn't contain a table:

> Table S3. The list of the experimentally validated drug-target network. This
> bipartite drug-target network matrix contains 5,680 experimentally validated drugtarget interactions connecting 732 approved drugs and 1,176 human targets. The
> “1” in the drug-target matrix denotes the experimentally validated drug-target
> interactions, while “0” represent the unknown drug-target interactions. (.xlsx)

It refers to those supplementary XLS spreadsheets I linked to above. We'd like to get the data from the second XLS sheet right?

**Comment by pnrobinson** [comment]
@justaddcoffee  I am really sorry, that was the wrong article:
https://www.nature.com/articles/s41421-020-0153-3#Sec25
I do not do well with multitasking, sorry I am also working on 3 grant proposals.
It is Supplemental Table S3 in this paper, in the PDF file!

**Comment by justaddcoffee** [comment]
No problem @pnrobinson! I haven't started on the PR yet, just making sure of the data we want. Should have a PR for this soon

**Comment by justaddcoffee** [comment]
Closing, this is addressed by #20
